### ISSUE TITLE
Laravel Blade Support - Feature Request

### ISSUE THREAD

**Issue by boxybird** [Luc45/ModernWordPressWebsite#2]
I'm really loving MWW! It's one the cleanest approaches I've seen. Everything feels modern... except for the PHP templating.

I think adding Laravel Blade would be awesome from a syntax prospective, you know the whole `{{ $post }}` thing. But where I like it would really shine is with directives. For example:

```
Blade::directive('loop', function () {
    return '<?php if (have_posts()) { while (have_posts()) { the_post(); ?>';
});

Blade::directive('endloop', function () {
    return '<?php }} ?>';
});

// Usage

@loop
    {{ get_the_title() }}
@endloop
```

**Comment by Luc45** [comment]
I like this idea!

At first, I tried to keep the framework unopinionated. But after all, I agree we should include a templating system.

Even though I like Blade's syntax, I think Twig is more mature for non-laravel projects.

Twig vs Blade was actually one of the reasons I didn't include any of them. But I think it's time to pick one! Thoughts?

**Comment by boxybird** [comment]
I've used both in WordPress, and to me, Blade is the easy winning (outside the "mature for non-laravel projects" argument). 

Twig is great in general, but because WP uses a lot function helpers in templates, ex: `get_the_title()`, it's a pain to call these functions without creating a custom wrapper in Twig. Especially if it's nested/outside the loop like: `get_the_title(get_the_ID())`.  

In Blade you can simply call `{{ get_the_title() }}` or `get_the_title(get_the_ID()) ` or `{!! get_the_content() !!}`, and it just works.

Timber (https://github.com/timber/timber) solved this Twig issue, but I think it's a bit clunky. I'll also think extending Blade feels better, like the directive example I used.

**Comment by Luc45** [comment]
Hey buddy.

Sorry for taking long to get back to you, it's been some busy days at work.

If you'd like to do a PR, I would love to review it, and if everything is right, I'm inclined to accept it :+1:

**Comment by boxybird** [comment]
Let me see what I can do.

Do you prefer I extend Blade as a view option, or replace the current option?

**Comment by Luc45** [comment]
If going down the templaters route, I prefer chosing one and sticking to it. So, replacing the current implementation seems good to me

**Comment by Luc45** [comment]
Merged on https://github.com/Luc45/ModernWordPressWebsite/pull/8

Closing this, thanks!
